# Generated by Django 2.1.5 on 2019-12-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191216_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(blank=True, default='date', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='', max_length=235),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summery',
            field=models.TextField(),
        ),
    ]
